services:
  - type: web
    plan: free
    runtime: docker
    name: hms-backend
    repo: https://github.com/AnkushRaheja/HMS_Micro.git
    branch: main
    dockerfilePath: Dockerfile
    dockerContext: .
    healthCheckPath: /actuator/health
    envVars:
      - key: GATEWAY_PORT
        value: 10000
      - key: EUREKA_HOST
        value: localhost
      - key: EUREKA_PORT
        value: 8761
      - key: AUTH_PORT
        value: 8084
      - key: PATIENT_PORT
        value: 8081
      - key: DOCTOR_PORT
        value: 8082
      - key: STAFF_PORT
        value: 8083
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_ALLOWED_ORIGINS
        sync: false
